name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Step1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "Hello world" > hello-world.txt
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-file
          path: hello-world.txt
  Step2:
    needs: Step1
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: hello-world-file
      - name: Log file
        run: cat hello-world.txt
