name: learn-deploy-self-host
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: pm2 start index.js
